#%RAML 1.0 DataType
type: array
items:
              type: object
              properties:
                name:
                  type: string
                  required: true
                  example: "dhoni"
                age:
                  type: number
                  required: true
                  example: 40
                place:
                  type: string
                  required: true
                  example: "mumbay"