#%RAML 1.0
title: title
types:
  getpost: !include title/dataType.raml
uses:
  resource: resourceType.raml
/cricket:
  type: {resource.collection: {getexample: !include /title/cricket.json,gettype: !include /title/dataType.raml }} 
  get: 

      
      
     
   
                    
          